### ISSUE TITLE
json problem in aos.devices.managed_devices.get_all()

### ISSUE THREAD

**Issue by sfuhrm** [Apstra/apstra-api-python#11]
Hi,

it looks like the JSON returned from the server contains less keys than the aos client expects:

```
>>> aos.devices.managed_devices.get_all()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/apstra-api-python/aos/devices.py", line 151, in get_all
    return list(self.iter_all())
  File "/root/apstra-api-python/aos/devices.py", line 157, in iter_all
    yield System.from_json(s)
  File "/root/apstra-api-python/aos/devices.py", line 65, in from_json
    user_config=d["user_config"],
KeyError: 'user_config'
>>> 
```
Any help would be appreciated.

Stephan

**Comment by azdolinski** [comment]
test.py
```python
from aos.client import AosClient

import urllib3
urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)

AOS_IP = "10.10.10.4"
AOS_PORT = 443
AOS_USER = "admin"
AOS_PW = "admin"

aos = AosClient(protocol="https", host=AOS_IP, port=AOS_PORT)
aos.auth.login(AOS_USER, AOS_PW)

devices = aos.devices.managed_devices.get_all()
print(devices)
```
for me it is working fine... / Apstra 4.0.2

can you tell more.. apstra version? API call trace from your GET /api/systems ?
example:
``
{"items":[{"container_status":{"error":"","host":"AosController","name":"aos-offbox-10_240_40_32-f","status":"running"},"device_key":"500032320000","facts":{"aos_hcl_model":"Juniper_vQFX","aos_server":"10.10.10.4","aos_version":"AOS_4.0.2_OB.142","chassis_mac_ranges":"00:00:6d:3e:00:00-00:00:6d:3e:00:3f,02:05:86:71:ac:00-02:05:86:71:ac:00","hw_model":"VQFX-10000","hw_version":"","mgmt_ifname":"em0","mgmt_ipaddr":"10.240.40.32","mgmt_macaddr":"50:00:32:32:00:00","os_arch":"x86_64","os_family":"Junos","os_version":"20.2R1.10","os_version_info":{"build":"10","major":"20","minor":"2R1"},"serial_number":"500032320000","vendor":"Juniper"},"id":"500032320000","status":{"agent_start_time":"2022-03-29T14:44:05.150295Z","blueprint_active":true,"blueprint_id":"DC1","comm_state":"on","device_start_time":"2022-03-23T15:32:31.000000Z","domain_name":"","error_message":"","fqdn":"Leaf-32","hostname":"Leaf-32","is_acknowledged":true,"operation_mode":"full_control","pool_id":"default_pool","state":"IS-ACTIVE"},"user_config":{"admin_state":"normal","aos_hcl_model":"Juniper_vQFX","location":""}}
``

**Comment by sfuhrm** [comment]
Apstra Version is 4.0.2-142

See the systems json attached:
[systems.json.gz](https://github.com/Apstra/apstra-api-python/files/8379876/systems.json.gz)

**Comment by azdolinski** [comment]
it looks like you have object which not have 'user_config' and that cause error.

```
    {
      "container_status": {
        "error": "",
        "host": "AosController",
        "name": "aos-offbox-172_16_105_140-f",
        "status": "running"
      },
      "device_key": "FDO2526xxxA",
      "facts": {
        "aos_hcl_model": "",
        "aos_server": "",
        "aos_version": "",
        "chassis_mac_ranges": "",
        "hw_model": "",
        "hw_version": "",
        "mgmt_ifname": "",
        "mgmt_ipaddr": "",
        "mgmt_macaddr": "",
        "os_arch": "",
        "os_family": "",
        "os_version": "",
        "os_version_info": {
          "build": "",
          "major": "",
          "minor": ""
        },
        "serial_number": "",
        "vendor": ""
      },
      "id": "FDO2526xxxA",
      "status": {
        "comm_state": "on",
        "error_message": "",
        "is_acknowledged": false,
        "operation_mode": "full_control",
        "state": "OOS-QUARANTINED"
      }
    },
```

**Comment by azdolinski** [comment]
Can you pleas check if this will prevent error?:

```diff
--- aos/devices.py.orig 2022-03-30 12:33:26.226789389 +0000
+++ aos/devices.py      2022-03-30 12:35:44.171095860 +0000
@@ -62,7 +62,7 @@
             facts=d["facts"],
             services=d.get("services", []),
             status=d["status"],
-            user_config=d["user_config"],
+            user_config=d.get("user_config"),
         )
```

**Comment by sfuhrm** [comment]
Thanks for the quick analysis! Unfortunately I don't have the possibility to try it. May be you can test it with the JSON I provided?
For "services" the JSON provides no entries and the code works, so I presume the fix also works for "user_config".

**Comment by sfuhrm** [comment]
Thanks for the quick help, guys!
