### ISSUE TITLE
AosAPIError: Routing zone with given ID does not exist

### ISSUE THREAD

**Issue by azdolinski** [Apstra/apstra-api-python#8]
**Expected Behavior:**
No error for new create_security_zone action

**Current Behavior:**
Traceback (most recent call last):
  File "code.py", line 83, in <module>
    sz = aos.blueprint.create_security_zone(
  File "/mnt/github/Apstra-aaC/aos/blueprint.py", line 1693, in create_security_zone
    repeat_until(
  File "/mnt/github/Apstra-aaC/aos/repeat.py", line 29, in repeat_until
    return repeat(
  File "/mnt/github/Apstra-aaC/aos/repeat.py", line 72, in repeat
    while _continue(stop_condition, error_condition, retval) and timeout > 0:
  File "/mnt/github/Apstra-aaC/aos/repeat.py", line 112, in _continue
    not stop_condition(*stop_args) if callable(stop_condition) else False
  File "/mnt/github/Apstra-aaC/aos/blueprint.py", line 1694, in <lambda>
    lambda: self.get_security_zone(bp_id, sz["id"]) != NullSecurityZone,
  File "/mnt/github/Apstra-aaC/aos/blueprint.py", line 1554, in get_security_zone
    self.rest.json_resp_get(
  File "/mnt/github/Apstra-aaC/aos/aos.py", line 237, in json_resp_get
    return self.raw_request_json("GET", uri, params, data, headers)
  File "/mnt/github/Apstra-aaC/aos/aos.py", line 120, in raw_request_json
    resp = self.raw_request(method, uri, params, data, headers)
  File "/mnt/github/Apstra-aaC/aos/aos.py", line 115, in raw_request
    raise AosAPIError(err_message(resp))
aos.aos.AosAPIError: Routing zone with given ID does not exist

**Steps to Reproduce:**
Code:
            # Create Routing-Zone
            sz = aos.blueprint.create_security_zone(					<--- "code.py", line 83
                bp_id=bp.id,
                name=vrf_name,
                vlan_id=vrf.get('vlan'),
                vni_id=vrf.get('vni'),
                leaf_loopback_ip_pools=[leaf_lo_pool.id]
                #dhcp_servers=[dhcp_rely_addr]
            )

**Context (Environment):**
Apstra 4.0.2 
Python 3.8.10

**Detailed Description:**
AosAPIError triggere for new create_security_zone action:
Based on "aos.blueprint.create_security_zone" - it looks like it doing 3 steps:
1) create RZ
2) check for ID which was been created for this RZ
3) assign leaf_loopback_ip_pools

based on checks - it looks like for most cases this 2nd step is too fast for Apstra API... and API return 404.
quick check -> add in bluprint.py / line 1692:
        import time
        time.sleep(2)
confirm that all looks to be fine when we just wait 2 secens between create and check just created RZ ID.

**Possible Implementation:**
repeat_until loop for checking ID for just createz RZ return 404 - and that trigere error.
raw_request will be not triggere critical "AosAPIError" for responses 404.

**Possible Solution:**
aos.py:
line 114:  -  elif resp.status_code >= 400:
line 114: +  elif resp.status_code >= 400 and resp.status_code != 404:

**Comment by azdolinski** [comment]
root@aos-server:~# ngrep -q -Wbyline  -d lo port 8888

T 127.0.0.1:39248 -> 127.0.0.1:8888 [AP] #714
POST /api/blueprints/DC1/security-zones HTTP/1.0.
x-user: admin.
x-user-id: fdf78319-6808-4c85-9fb3-5c989779607d.
Host: 10.10.10.4.
X-Real-IP: 192.168.1.1.
X-Forwarded-For: 192.168.1.1.
X-Forwarded-Proto: https.
Connection: close.
Content-Length: 266.
User-Agent: python-requests/2.25.1.
Accept-Encoding: gzip, deflate.
Accept: application/json.
Content-Type: application/json.
AuthToken: eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwiY3JlYXRlZF9hdCI6IjIwMjItMDMtMjdUMTU6NTU6NTEuMjA0MDE5IiwidXNlcl9zZXNzaW9uIjoiMmU1MDc0NzQtMDJkMS00YWU2LTljYTYtOWE3ZDcxY2U3ZjNlIiwiZXhwIjoxNjQ4NDgyOTUxfQ.fQLjTxLxnrvcKqvcMAsM48vm5cy3FllAfOz_0q_hIrg7CgiPyRjRQk6C2qg-4Fn5wxUIIQj8hxLbjlkjWPEW3g.
.
{"routing_policy": {"export_policy": {"spine_leaf_links": false, "loopbacks": true, "l2edge_subnets": true, "l3edge_server_links": false}, "import_policy": "default_only"}, "sz_type": "evpn", "label": "Mirinda", "vrf_name": "Mirinda", "vlan_id": 60, "vni_id": 10060}

T 127.0.0.1:8888 -> 127.0.0.1:39248 [AP] #716
HTTP/1.0 201 CREATED.
Content-Type: application/json.
Transfer-Encoding: chunked.
Date: Sun, 27 Mar 2022 15:55:51 GMT.
.


T 127.0.0.1:8888 -> 127.0.0.1:39248 [AP] #718
2e.
{"id": "dc379cbc-6c98-4283-abac-2629d94b0634"}.


T 127.0.0.1:8888 -> 127.0.0.1:39248 [AP] #720
0.
.


T 127.0.0.1:39252 -> 127.0.0.1:8888 [AP] #728
GET /api/blueprints/DC1/security-zones/dc379cbc-6c98-4283-abac-2629d94b0634 HTTP/1.0.
x-user: admin.
x-user-id: fdf78319-6808-4c85-9fb3-5c989779607d.
Host: 10.10.10.4.
X-Real-IP: 192.168.1.1.
X-Forwarded-For: 192.168.1.1.
X-Forwarded-Proto: https.
Connection: close.
User-Agent: python-requests/2.25.1.
Accept-Encoding: gzip, deflate.
Accept: application/json.
Content-Type: application/json.
AuthToken: eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwiY3JlYXRlZF9hdCI6IjIwMjItMDMtMjdUMTU6NTU6NTEuMjA0MDE5IiwidXNlcl9zZXNzaW9uIjoiMmU1MDc0NzQtMDJkMS00YWU2LTljYTYtOWE3ZDcxY2U3ZjNlIiwiZXhwIjoxNjQ4NDgyOTUxfQ.fQLjTxLxnrvcKqvcMAsM48vm5cy3FllAfOz_0q_hIrg7CgiPyRjRQk6C2qg-4Fn5wxUIIQj8hxLbjlkjWPEW3g.
.


T 127.0.0.1:8888 -> 127.0.0.1:39252 [AP] #730
HTTP/1.0 404 NOT FOUND.
Content-Type: application/json.
Cache-Control: no-cache.
Transfer-Encoding: chunked.
Date: Sun, 27 Mar 2022 15:55:51 GMT.
.


T 127.0.0.1:8888 -> 127.0.0.1:39252 [AP] #732
37.
{"errors": "Routing zone with given ID does not exist"}.


T 127.0.0.1:8888 -> 127.0.0.1:39252 [AP] #734
0.
.

**Comment by that1guy15** [comment]
This issue was resolved with the commit to main here. https://github.com/Apstra/apstra-api-python/commit/b2d890a1be6306f90b058c72282f1103d5ecd4fc.
